name = "MPSKitModels"
uuid = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
authors = ["Maarten Van Damme", "Gertian Roose", "Klaas Gunst"]
version = "0.2.2"

[deps]
InitialValues = "22cec73e-a1b8-11e9-2c92-598750a2cf9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MPSKit = "0.6 - 0.7"
TensorKit = "0.10"
julia = "1"
InitialValues = "0.3"
